# -*- coding: utf-8 -*-
"""12th heart disease project .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G4ru2-Ktu_X3b9Z0-ZzLDWt0XpnTCRR2
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('/content/heart_disease_uci.csv')

df.head()

df.info()

# Statistical summary
display(df.describe())
display(df.isnull().sum())

# Histograms
df.hist(figsize=(12,10))
plt.tight_layout()
plt.show()

# Viewing target distribution
sns.countplot(x='num', data=df)
plt.title('Target Distribution (num)')
plt.show()

# Boxplots to spot outliers
cols = ['age', 'trestbps', 'chol', 'thalch', 'oldpeak']
plt.figure(figsize=(15, 8))
for i, col in enumerate(cols, 1):
    plt.subplot(2, 3, i)
    sns.boxplot(y=df[col])
    plt.title(col)
plt.tight_layout()
plt.show()

# Data Cleaning

df = df.replace('?', np.nan)
df = df.apply(pd.to_numeric, errors='ignore')

# Drop useless and high-null columns
df = df.drop(columns=['id', 'dataset', 'ca', 'thal'])

# Fix invalid zeros
for col in ['chol', 'trestbps']:
    df[col] = df[col].replace(0, np.nan)

# Fill nulls — numerical with median
for col in ['trestbps', 'chol', 'thalch', 'oldpeak']:
    df[col] = df[col].fillna(df[col].median())

# Fill nulls — categorical with mode
for col in ['slope', 'fbs', 'restecg', 'exang']:
    df[col] = df[col].fillna(df[col].mode()[0])

# Convert target to binary
df['num'] = (df['num'] > 0).astype(int)

df.head()

display(df.isnull().sum())
display(df.shape)

# Post-cleaning Visualization(for discovering relationships)

# 1. Correlation Heatmap
plt.figure(figsize=(10, 8))
sns.heatmap(df.corr(numeric_only=True), annot=True, fmt='.2f', cmap='coolwarm')
plt.title('Correlation Heatmap')
plt.show()

# All numerical columns vs num — boxplots
num_cols = ['age', 'thalch', 'chol', 'trestbps', 'oldpeak']
plt.figure(figsize=(15, 8))
for i, col in enumerate(num_cols, 1):
    plt.subplot(2, 3, i)
    sns.boxplot(x='num', y=col, data=df)
    plt.title(col + ' vs Heart Disease')
    plt.xlabel('Heart Disease (0=No, 1=Yes)')
plt.tight_layout()
plt.show()

# All categorical columns vs num — countplots
cat_cols = ['sex', 'cp', 'exang', 'slope', 'restecg', 'fbs']
plt.figure(figsize=(18, 10))
for i, col in enumerate(cat_cols, 1):
    plt.subplot(2, 3, i)
    sns.countplot(x=col, hue='num', data=df)
    plt.title(col + ' vs Heart Disease')
    plt.legend(title='Disease', labels=['No', 'Yes'])
plt.tight_layout()
plt.show()

# Encoding

# Convert booleans to integers
df['exang'] = df['exang'].astype(int)
df['fbs'] = df['fbs'].astype(int)

# One-hot encode categorical columns
df = pd.get_dummies(df, columns=['sex', 'cp', 'restecg', 'slope'], drop_first=False, dtype=int)

# Confirm result
display(df.head())
display(df.shape)

# Split then Scale the data
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Separate features and target
X = df.drop(columns=['num'])
y = df['num']

# Split 80/20
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Scale numerical columns only
num_cols = ['age', 'trestbps', 'chol', 'thalch', 'oldpeak']
scaler = StandardScaler()

X_train[num_cols] = scaler.fit_transform(X_train[num_cols])
X_test[num_cols] = scaler.transform(X_test[num_cols])

print("Training size:", X_train.shape)
print("Testing size:", X_test.shape)

# Logistic Regression
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Train the model
model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)

# Accuracy
print("Accuracy:", accuracy_score(y_test, y_pred))

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=['No Disease', 'Disease'],
            yticklabels=['No Disease', 'Disease'])
plt.title('Confusion Matrix')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.show()

# Classification Report
print(classification_report(y_test, y_pred))